#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo '🏗️👷 Styling, testing and building your project before committing'

# Check Prettier standards
yarn run format:check ||
(
  echo '🤢🤮🤢🤮 Your styling looks disgusting. 🤢🤮🤢🤮
  Prettier Check Failed. Run yarn run format:write, add changes and try commit again.';
  false;
)

# Check ESLint Standards
yarn run lint ||
(
  echo '😤🏀👋😤 Get them scripts out of here! 😤🏀👋😤
  ESLint Check Failed. Make the required changes listed above, run yarn run lint:fix and try to commit again.'
  false;
)

# If everything passes... Now we can commit
echo '✅✅✅✅ You win this time... I am committing this now. ✅✅✅✅'